format = """
$username\
$hostname\
$directory\
$aws\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$terraform\
$fill\
$python\
$cmd_duration $jobs $time\
$line_break\
$character"""

# ~/.config/starship.toml

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) || "
disabled = false
show_always = true

[aws]
format = ' | aws ($profile )(\($region\) )(\[$duration\] )'

[python]
format = ' | py ${pyenv_prefix}(${version} )(\($virtualenv\) )'

[terraform]
format = " | terr - $workspace"

[fill]
symbol = " "

[directory]
style = "blue"
read_only = " ^"
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "❯"
vicmd_symbol = "❮"

[git_branch]
format = " | git $branch "
style = "bright-black"

# ~/.config/starship.toml

[jobs]
symbol = "+ "
number_threshold = 4
symbol_threshold = 0
